### ISSUE TITLE
Multiple Galleries

### ISSUE THREAD

**Issue by signalwerk** [daniellienert/DL.Gallery#14]
It would be great if we would have the option to define multiple Galleries with different settings but the same theme. Instead of:

```
bootstrapLightbox:
  label: 'Bootstrap with Lightbox'
  themeSettings:
    ...
    imageVariants:
      thumb:
        ...
      large:
        ..
```

it would be great to have something like: 

```
someTitle:                           # <---- to define by user
  label: 'Bootstrap with Lightbox'   # <---- to define by user
  themeSettings:
    theme: bootstrapLightbox         # <---- here we reference the theme 
    ...
    imageVariants:
      thumb:
        ...                          # <---- here some custom settings
      large:
        ..
```

with such a setting you could have multiple settings with the same theme. This could be done with not breaking existing installations.

**Comment by daniellienert** [comment]
Hey @signalwerk, 
In order to make the extension more flexible and extendable I refactored it towards the Fusion Components concept. In current master / 2.x it will be possible to define the rendering fusion prototype. That will make the following possible:

```
DL:
  Gallery:
    themes:
      anotherBootstrapGallery: # <-- defined by user
        label: 'Bootstrap with Lightbox' <-- defined by user
        fusionPrototype: 'DL.Gallery:Themes.BootstrapLightbox'
        themeSettings:
        ....
```

Would that fulfill your needs?
