### ISSUE TITLE
How can I add a second theme

### ISSUE THREAD

**Issue by stefkey** [daniellienert/DL.Gallery#2]
Hi, what things is to do to have a second theme?

I have add it in the Settings.yaml, so in the backend there is the second theme. But in frontend there is no change.

**Comment by daniellienert** [comment]
Hey @stefkey, 
It depends what You want to achieve with your theme. Via the settings, you can easily exchange the CSS and JS that is used. The Fluid template though is currently selected only from a fixed folder in the Plugin.
If you want to overwrite that, you currently have to overwrite the TypoScript within your package.

**Comment by stefkey** [comment]
Hey @daniellienert,

thanks for your answer. I would like to use 2 layouts. One with 3 column, one with 6 column. I thought I'd choose a template in the inspector. What do you think to put in this features? Tow templates, or another solution?

**Comment by dgrammlich** [comment]
Hey @daniellienert,

I have a similar case. My goal is a slider with your gallery beneath it. I've tried it like this in the `Settings.yaml`:

```
DL:
  Gallery:
    loadGalleryCSS: true
    loadGalleryJS: true
    themes:
      bootstrapLightbox:
        label: 'Bootstrap with Lightbox'
        themeSettings:
          galleryCSS: 'resource://DL.Gallery/Public/Styles/BootstrapLightbox.css'
          galleryJS: 'resource://DL.Gallery/Public/JavaScript/BootstrapLightbox.min.js'
          columnClass: 'col-md-3'
          imageVariants:
            thumb:
              maximumWidth: 350
              maximumHeight: 350
              width: 262
              height: 262
      danis:
        label: 'Danis Theme'
        themeSettings:
          columnClass: 'col-md-12'
          imageVariants:
            thumb:
              width: 262
              height: 262
```

I can change the theme in the inspector, but the `columnClass` stays `col-md-3` instead of changing to `col-md-12`. Is this the way to go? What did I do wrong?

Thanks in advance. :)
